In [99]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [100]:
df=pd.read_csv("./Final_Combined_Dataset.csv")
df=df.set_index(keys="zpid")
df

,bedrooms,bathrooms,price,zipcode,hdpUrl,cityId,homeType,livingArea,livingAreaValue,rentZestimate,...,originalPhotos,address.streetAddress,address.city,address.state,address.zipcode,image_captions,leisure_within_5km,shops_within_5km,schools_within_5km,transit_within_2km
zpid,,,,,,,,,,,,,,,,,,,,,
100650,3.0,2.0,122400,35172,/homedetails/513-Hagwood-Cir-Trafford-AL-35172...,NaN,SINGLE_FAMILY,1400.0,1400.0,1200.0,...,['https://photos.zillowstatic.com/fp/933bbfddb...,513 Hagwood Cir,Trafford,AL,35172,a photograph of a house in the woods with a po...,0,0,0,0
394191,2.0,2.0,1475000,20037,/homedetails/2555-Pennsylvania-Ave-NW-APT-501-...,41568.0,CONDO,1590.0,1590.0,NaN,...,['https://photos.zillowstatic.com/fp/7728b70d7...,2555 Pennsylvania Ave NW APT 501,Washington,DC,20037,a photograph of a large building with a lot of...,16,167,118,159
394956,2.0,3.0,1200000,20037,/homedetails/800-25th-St-NW-1001-Washington-DC...,41568.0,CONDO,2007.0,2007.0,6999.0,...,['https://photos.zillowstatic.com/fp/947993164...,800 25th St NW #1001,Washington,DC,20037,a photograph of a building with cars parked in...,14,161,104,150
395184,0.0,1.0,255000,20037,/homedetails/922-24th-St-NW-APT-309-Washington...,41568.0,APARTMENT,498.0,498.0,1892.0,...,['https://photos.zillowstatic.com/fp/0a2f90e81...,922 24th St NW APT 309,Washington,DC,20037,a photograph of a large building with a lot of...,17,168,108,168
395274,0.0,1.0,285000,20037,/homedetails/922-24th-St-NW-APT-820-Washington...,41568.0,CONDO,465.0,465.0,1914.0,...,['https://photos.zillowstatic.com/fp/dcf342b52...,922 24th St NW APT 820,Washington,DC,20037,"a photograph of a bedroom with a bed, couch, a...",17,168,108,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140770427,2.0,2.0,236800,94089,/homedetails/1111-Morse-Ave-SPC-101-Sunnyvale-...,54626.0,MANUFACTURED,1440.0,1440.0,464.0,...,['https://photos.zillowstatic.com/fp/5577a7caa...,1111 Morse Ave SPC 101,Sunnyvale,CA,94089,a photograph of a mobile home with a flag on t...,0,0,0,0
2141107496,10.0,4.0,395000,60609,/homedetails/1822-W-46th-St-Chicago-IL-60609/2...,17426.0,MULTI_FAMILY,NaN,NaN,NaN,...,['https://photos.zillowstatic.com/fp/91d4eff7c...,1822 W 46th St,Chicago,IL,60609,a photograph of a two story brick building wit...,0,33,41,186
2144732235,2.0,2.0,1650000,2116,/homedetails/221-Columbus-Ave-APT-603-Boston-M...,44269.0,CONDO,1508.0,1508.0,5726.0,...,['https://photos.zillowstatic.com/fp/9d1560a0d...,221 Columbus Ave APT 603,Boston,MA,2116,a photograph of a building with a large entran...,0,0,0,0
2146966820,2.0,2.0,2950000,94114,/homedetails/760-Church-St-3-San-Francisco-CA-...,20330.0,CONDO,1622.0,1622.0,5068.0,...,['https://photos.zillowstatic.com/fp/c9a9f7e88...,760 Church St #3,San Francisco,CA,94114,a photograph of a rooftop deck with a view of ...,10,323,68,461
2146972089,2.0,1.0,159000,60004,/homedetails/4214-Bonhill-Dr-APT-3F-Arlington-...,50764.0,CONDO,900.0,900.0,1450.0,...,['https://photos.zillowstatic.com/fp/83e68a72f...,4214 Bonhill Dr APT 3F,Arlington Heights,IL,60004,a photograph of a building with a car parked i...,0,0,0,0

In [101]:
df.columns

Index(['bedrooms', 'bathrooms', 'price', 'zipcode', 'hdpUrl', 'cityId',
       'homeType', 'livingArea', 'livingAreaValue', 'rentZestimate',
       'description', 'latitude', 'longitude', 'homeInsights', 'photoCount',
       'originalPhotos', 'address.streetAddress', 'address.city',
       'address.state', 'address.zipcode', 'image_captions',
       'leisure_within_5km', 'shops_within_5km', 'schools_within_5km',
       'transit_within_2km'],
      dtype='object')

In [102]:
df1=df.drop(columns=['zipcode','hdpUrl','cityId','livingAreaValue','rentZestimate','photoCount','address.streetAddress','originalPhotos','latitude','longitude'])

df1

,bedrooms,bathrooms,price,homeType,livingArea,description,homeInsights,address.city,address.state,address.zipcode,image_captions,leisure_within_5km,shops_within_5km,schools_within_5km,transit_within_2km
zpid,,,,,,,,,,,,,,,
100650,3.0,2.0,122400,SINGLE_FAMILY,1400.0,REO Occupied – NO ACCESS OR VIEWINGS of this p...,[{'insights': [{'modelId': 'v2-2-backfill-samp...,Trafford,AL,35172,a photograph of a house in the woods with a po...,0,0,0,0
394191,2.0,2.0,1475000,CONDO,1590.0,OPEN SATURDAY AND SUNDAY - 1-4 ! RARELY AVAILA...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,a photograph of a large building with a lot of...,16,167,118,159
394956,2.0,3.0,1200000,CONDO,2007.0,NEW ON THE MARKET! Estate Sale being sold stri...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,a photograph of a building with cars parked in...,14,161,104,150
395184,0.0,1.0,255000,APARTMENT,498.0,Beautiful studio condominium located in the vi...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,a photograph of a large building with a lot of...,17,168,108,168
395274,0.0,1.0,285000,CONDO,465.0,Luxury living in the heart of Foggy Bottom. We...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,"a photograph of a bedroom with a bed, couch, a...",17,168,108,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140770427,2.0,2.0,236800,MANUFACTURED,1440.0,Your home awaits in this recently updated 2-be...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Sunnyvale,CA,94089,a photograph of a mobile home with a flag on t...,0,0,0,0
2141107496,10.0,4.0,395000,MULTI_FAMILY,NaN,SOLID BRICK BUILDING WITH 4 legal unit PLUS 1 ...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Chicago,IL,60609,a photograph of a two story brick building wit...,0,33,41,186
2144732235,2.0,2.0,1650000,CONDO,1508.0,Iconic South End architecture at the Albert A....,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Boston,MA,2116,a photograph of a building with a large entran...,0,0,0,0
2146966820,2.0,2.0,2950000,CONDO,1622.0,Stunning penthouse unit in a Dolores Park Trop...,"[{'insights': [{'modelId': 'v2-2-llm-correct',...",San Francisco,CA,94114,a photograph of a rooftop deck with a view of ...,10,323,68,461
2146972089,2.0,1.0,159000,CONDO,900.0,Great chance to own this updated & ready to mo...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Arlington Heights,IL,60004,a photograph of a building with a car parked i...,0,0,0,0

In [103]:
null_percentage = (df1.isnull().sum() / len(df1)) * 100
null_percentage

bedrooms              1.831027
bathrooms             1.715686
price                 0.000000
homeType              0.000000
livingArea            1.485006
description           1.196655
homeInsights          5.017301
address.city          0.000000
address.state         0.000000
address.zipcode       0.000000
image_captions        0.432526
leisure_within_5km    0.000000
shops_within_5km      0.000000
schools_within_5km    0.000000
transit_within_2km    0.000000
dtype: float64

In [104]:
df1['leisure_within_5km'].median(),df1['transit_within_2km'].median(),df1['schools_within_5km'].median(),df1['transit_within_2km'].median()

(0.0, 0.0, 1.0, 0.0)

In [105]:
mode_value = df1['bedrooms'].mode()[0]
mod_1=df1['bathrooms'].mode()[0]
living_mod=df1['livingArea'].mean()
# Replace null values with the mode
df1['bedrooms']=df1['bedrooms'].fillna(mode_value)
df1['bathrooms']=df1['bathrooms'].fillna(mod_1)
df1['livingArea']=df1['livingArea'].fillna(living_mod)

columns_to_check = ['description', 'homeInsights','image_captions']

# Remove rows with all null values in specified columns
df1 = df1.dropna(subset=columns_to_check, how='all')
df1

,bedrooms,bathrooms,price,homeType,livingArea,description,homeInsights,address.city,address.state,address.zipcode,image_captions,leisure_within_5km,shops_within_5km,schools_within_5km,transit_within_2km
zpid,,,,,,,,,,,,,,,
100650,3.0,2.0,122400,SINGLE_FAMILY,1400.000000,REO Occupied – NO ACCESS OR VIEWINGS of this p...,[{'insights': [{'modelId': 'v2-2-backfill-samp...,Trafford,AL,35172,a photograph of a house in the woods with a po...,0,0,0,0
394191,2.0,2.0,1475000,CONDO,1590.000000,OPEN SATURDAY AND SUNDAY - 1-4 ! RARELY AVAILA...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,a photograph of a large building with a lot of...,16,167,118,159
394956,2.0,3.0,1200000,CONDO,2007.000000,NEW ON THE MARKET! Estate Sale being sold stri...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,a photograph of a building with cars parked in...,14,161,104,150
395184,0.0,1.0,255000,APARTMENT,498.000000,Beautiful studio condominium located in the vi...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,a photograph of a large building with a lot of...,17,168,108,168
395274,0.0,1.0,285000,CONDO,465.000000,Luxury living in the heart of Foggy Bottom. We...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Washington,DC,20037,"a photograph of a bedroom with a bed, couch, a...",17,168,108,170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2140770427,2.0,2.0,236800,MANUFACTURED,1440.000000,Your home awaits in this recently updated 2-be...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Sunnyvale,CA,94089,a photograph of a mobile home with a flag on t...,0,0,0,0
2141107496,10.0,4.0,395000,MULTI_FAMILY,1820.995024,SOLID BRICK BUILDING WITH 4 legal unit PLUS 1 ...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Chicago,IL,60609,a photograph of a two story brick building wit...,0,33,41,186
2144732235,2.0,2.0,1650000,CONDO,1508.000000,Iconic South End architecture at the Albert A....,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Boston,MA,2116,a photograph of a building with a large entran...,0,0,0,0
2146966820,2.0,2.0,2950000,CONDO,1622.000000,Stunning penthouse unit in a Dolores Park Trop...,"[{'insights': [{'modelId': 'v2-2-llm-correct',...",San Francisco,CA,94114,a photograph of a rooftop deck with a view of ...,10,323,68,461
2146972089,2.0,1.0,159000,CONDO,900.000000,Great chance to own this updated & ready to mo...,"[{'insights': [{'modelId': 'z-nrt-pdc-tags', '...",Arlington Heights,IL,60004,a photograph of a building with a car parked i...,0,0,0,0

In [106]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt


label_encoder = LabelEncoder()
df1['homeType'] = label_encoder.fit_transform(df1['homeType'])

C:\Users\kalya\AppData\Local\Temp\ipykernel_10348\3433511660.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['homeType'] = label_encoder.fit_transform(df1['homeType'])

In [107]:
dfs_by_category = {}

# Get unique values in the 'Category' column
unique_categories = df1['address.state'].unique()

# Iterate over unique categories
for category in unique_categories:
    # Filter the DataFrame for the current category
    filtered_df = df1[df1['address.state'] == category]
    
    # Add the filtered DataFrame to the dictionary with category as the key
    dfs_by_category[category] = filtered_df

# Access the DataFrames using category keys
for category, df_category in dfs_by_category.items():
    print(f"Category: {category}")
    print(len(df_category))
    # print(df_category)

Category: AL
110
Category: DC
497
Category: IL
500
Category: NV
494
Category: Las Vegas
1
Category: AZ
496
Category: PA
497
Category: GA
494
Category: CA
1296
Category: TX
559
Category: NY
500
Category: FL
500
Category: MA
494
Category: MI
496
Category: ['https://photos.zillowstatic.com/fp/b721ed70b8f89663562a09d6a0bc0c0f-o_a.jpg', 'https://photos.zillowstatic.com/fp/7748fb50d89a7bf4233a5d85c16fde42-o_a.jpg', 'https://photos.zillowstatic.com/fp/ecfba145de869f95ceb6ef3caa481797-o_a.jpg', 'https://photos.zillowstatic.com/fp/b610ce04c006a420be34dc4362e99702-o_a.jpg', 'https://photos.zillowstatic.com/fp/71568e02f22bbfcdfdea6042ea5a102d-o_a.jpg', 'https://photos.zillowstatic.com/fp/e4e06bd81379cfbc3bfcd420244f9a96-o_a.jpg', 'https://photos.zillowstatic.com/fp/696adb577dc147576dae7f1a279dc453-o_a.jpg', 'https://photos.zillowstatic.com/fp/b18a2ae772d329a4e5693f88c73c9b11-o_a.jpg', 'https://photos.zillowstatic.com/fp/5ca6266575b5ae8505b12870cf26f38d-o_a.jpg', 'https://photos.zillowstatic.com/fp/f6adcb2297f810d7e1601daf131eb699-o_a.jpg', 'https://photos.zillowstatic.com/fp/4a8fa6d405674412ff9390ed68c94fee-o_a.jpg', 'https://photos.zillowstatic.com/fp/8212e88e3c5866b23bedaf4edf09be15-o_a.jpg', 'https://photos.zillowstatic.com/fp/e070702e71677616723b03b8b35c03c6-o_a.jpg', 'https://photos.zillowstatic.com/fp/dc7edc1224e28176aeb57a619bb8b086-o_a.jpg', 'https://photos.zillowstatic.com/fp/da78f1ff24076d671976906e91292881-o_a.jpg', 'https://photos.zillowstatic.com/fp/d8b66bcbfd3fe011668bc61a21bb7459-o_a.jpg', 'https://photos.zillowstatic.com/fp/430cfc9422632b0a1b40d9f93691e8e5-o_a.jpg', 'https://photos.zillowstatic.com/fp/9a11f572d55e5d951ce1a8c71b8cad52-o_a.jpg', 'https://photos.zillowstatic.com/fp/aaf0d74fdf7d7d90cda6194368b2afb6-o_a.jpg', 'https://photos.zillowstatic.com/fp/d2b96c7b1d770ac9062f19befd8ae14d-o_a.jpg', 'https://photos.zillowstatic.com/fp/57d5753396cbe26ffda408b01a725a1b-o_a.jpg', 'https://photos.zillowstatic.com/fp/7c296723d81046078e278488f03bdd0a-o_a.jpg', 'https://photos.zillowstatic.com/fp/2998cec13b4bd76e6735ee3b36a35d0a-o_a.jpg', 'https://photos.zillowstatic.com/fp/15099d5aceab94cb84ec3aea58a61f6f-o_a.jpg', 'https://photos.zillowstatic.com/fp/0b35c5869778375bb08947db6953d4f4-o_a.jpg', 'https://photos.zillowstatic.com/fp/e16250892f30e7f6365abc70e49f0094-o_a.jpg', 'https://photos.zillowstatic.com/fp/3dd59a2ff0262e82e858354bbfa021b0-o_a.jpg', 'https://photos.zillowstatic.com/fp/388cfbc6391d4dd470bee3a253b19167-o_a.jpg', 'https://photos.zillowstatic.com/fp/6ebe5d7d69c1a3f44fef11b58a32eb9c-o_a.jpg', 'https://photos.zillowstatic.com/fp/1d8edfa772e0ff22c7d0b1d52709bda1-o_a.jpg', 'https://photos.zillowstatic.com/fp/3423f1277cbd1f53e1f45f05749d9d16-o_a.jpg', 'https://photos.zillowstatic.com/fp/7fa3cafdff1f74075b3406f521124976-o_a.jpg', 'https://photos.zillowstatic.com/fp/35c5756b952b1445319a9d5d3e94d51a-o_a.jpg', 'https://photos.zillowstatic.com/fp/6c20c8d3243fdff8fc658162ca5c705f-o_a.jpg', 'https://photos.zillowstatic.com/fp/0fada90430aa9f0cde01218f87596d36-o_a.jpg', 'https://photos.zillowstatic.com/fp/85babeb8506dcdf41ba81155dd2ba01f-o_a.jpg', 'https://photos.zillowstatic.com/fp/d7478059854120efb5aaa6a602a7c93f-o_a.jpg', 'https://photos.zillowstatic.com/fp/674c630060b013a9a451a5d66edef5de-o_a.jpg', 'https://photos.zillowstatic.com/fp/7bf9bb9e6d605b1abbb35b6efc147d9a-o_a.jpg', 'https://photos.zillowstatic.com/fp/8e30dbd61f8529467cc75ee83b630990-o_a.jpg', 'https://photos.zillowstatic.com/fp/2b6a64d3a5c369f2e1e859763c83b455-o_a.jpg', 'https://photos.zillowstatic.com/fp/4322916152cb4538206e2b29651ce02b-o_a.jpg', 'https://photos.zillowstatic.com/fp/819179f109f2edcc2e0bc81db68c98b9-o_a.jpg', 'https://photos.zillowstatic.com/fp/eb06b7b82d8e35e39dc9f8ae473d7366-o_a.jpg', 'https://photos.zillowstatic.com/fp/cf6710a0b50240b29e241bce9595dd95-o_a.jpg', 'https://photos.zillowstatic.com/fp/3656be6094b2b8ef15fdb12aa77c1af7-o_a.jpg', 'https://photos.zillowstatic.com/fp/7ae31b12f9d91bd7c856acaee93ab4ff-o_a.jpg', 'https://photos.zillowstatic.com/fp/b0b326374bbf60a0d0c49ceade630080-o_a.jpg', 'https://photos.zillowstatic.com/fp/5751de6f5be80b45aa5d016272af0e8c-o_a.jpg', 'https://photos.zillowstatic.com/fp/cfd417b7b292da45a22aec9098c6e346-o_a.jpg', 'https://photos.zillowstatic.com/fp/5b1a992aeccff441efed43e9d6b2e3a4-o_a.jpg', 'https://photos.zillowstatic.com/fp/39257cc6e2beeb0a8f6bb15d4a20cccb-o_a.jpg', 'https://photos.zillowstatic.com/fp/7815a803ff252aef4e414c76e341aaa6-o_a.jpg', 'https://photos.zillowstatic.com/fp/73fd0f1818111b49d643bf4b758eaf0b-o_a.jpg']
1

In [108]:
MSE= {}
for key,value in dfs_by_category.items():
    if(len(value)>20):
        df_check=value
        df_check=df_check.drop(columns=['description','homeInsights','image_captions','address.city','address.state','address.zipcode'])
        scaler=StandardScaler()

        df_to_transform = df_check.drop(columns=['homeType'])
        df_excluded = df_check[['homeType']]
        # Apply the transformation
        scaler = StandardScaler()
        transformed_array = scaler.fit_transform(df_to_transform)
        df_transformed = pd.DataFrame(transformed_array, columns=df_to_transform.columns, index=df_check.index)
        # Recombine the DataFrame
        df_result = pd.concat([df_transformed, df_excluded], axis=1)
        # print(df_result)
        X=df_result.values
        weights = [5,5,1,1,1,1,1,1,1]
        X=X*weights
        print(X[:5])
        sse = []           
        kmeans = KMeans(n_clusters=12,init='k-means++', random_state=42)
        if(key=='CA'):
            kmeans = KMeans(n_clusters=24,init='k-means++', random_state=42)

        kmeans.fit(X)
        sse.append(kmeans.inertia_) 
        
        MSE[key]=sse

[[-1.41087747 -0.77083991 -0.18965535 -0.49052337  0.          0.
   0.          0.          4.        ]
 [-1.41087747 -4.37902672 -0.64169884 -0.58086867  0.          0.
   0.          0.          4.        ]
 [-1.41087747 -0.77083991 -0.17140514 -0.28916056  0.          0.
   0.          0.          4.        ]
 [-5.8450638  -4.37902672 -0.90141327 -0.93765602  0.          0.
   0.          0.          4.        ]
 [-5.8450638  -4.37902672 -0.90141327 -1.01115728  0.          0.
   0.          0.          4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

[[-2.4376622  -1.81539916  0.72182538 -0.08957302 -0.64421247  0.44483287
   0.2431918   0.96140614  1.        ]
 [-2.4376622   1.69531439  0.36994031  0.29243996 -0.97720632  0.33539539
  -0.11044008  0.84054813  1.        ]
 [-8.19309267 -5.3261127  -0.83926476 -1.08995232 -0.47771554  0.46307245
  -0.0094024   1.08226414  0.        ]
 [-8.19309267 -5.3261127  -0.8008773  -1.12018356 -0.47771554  0.46307245
  -0.0094024   1.10912148  1.        ]
 [-5.31537744 -5.3261127  -0.60254208 -0.96444686 -0.47771554  0.57250992
   0.34422947  1.49855284  1.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-3.74357346 -5.8371037  -0.51229425 -0.57095553 -0.63457871 -0.78874508
  -0.90437608 -0.95821221  1.        ]
 [-0.79122846  3.3263244  -0.10891354  0.1647506  -0.63457871 -0.78874508
  -0.90437608 -0.95821221  4.        ]
 [ 2.16111654  3.3263244   0.76850969  1.05015972 -0.63457871 -0.78874508
  -0.90437608 -0.95821221  4.        ]
 [ 5.11346153  7.90803845  0.71024879  1.46884776 -0.63457871 -0.78874508
  -0.90437608 -0.95821221  4.        ]
 [-0.79122846 -1.25538965  0.12506598 -0.19069393 -0.63457871 -0.78874508
  -0.90437608 -0.95821221  4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-5.11781241 -3.4425036  -0.289992   -0.14563293 -0.51675354 -0.67886855
  -0.55470762 -0.35351217  5.        ]
 [-0.64312333 -3.4425036  -0.25089874 -0.31337145 -0.51675354 -0.67886855
  -0.55470762 -0.35351217  4.        ]
 [-0.64312333 -4.70127249 -0.1392037  -0.0798718  -0.51675354 -0.67886855
  -0.55470762 -0.35351217  2.        ]
 [ 3.83156575 -3.4425036  -0.2788225  -0.4448937  -0.51675354 -0.67886855
  -0.55470762 -0.35351217  4.        ]
 [ 3.83156575 -3.4425036  -0.36631695 -0.58118125 -0.51675354 -0.67886855
  -0.55470762 -0.35351217  4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-4.68640175 -2.63249848 -0.43284603 -0.87813548 -0.36369152 -0.43680982
  -0.40738768 -0.43350714  4.        ]
 [-0.81230964 -2.63249848 -0.22492375  0.01458078 -0.36369152 -0.43680982
  -0.40738768 -0.43350714  4.        ]
 [ 3.06178248 -2.63249848 -0.21930727  0.0181233  -0.36369152 -0.43680982
  -0.40738768 -0.43350714  4.        ]
 [ 3.06178248 -2.63249848 -0.37668118 -0.34675676  0.9066676   0.96369225
   0.85991447  2.25100278  4.        ]
 [-0.81230964 -2.63249848 -0.46643261 -0.82499761  0.9066676   0.96369225
   0.71910312  2.21865928  4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-0.3975649  -0.2760382   0.04987984 -0.17824265  1.03809246  0.63325886
  -0.31574355 -0.15338575  5.        ]
 [-0.3975649  -4.92658011  0.27717173  0.06600939  1.31637291  0.66973234
  -0.21960844 -0.0206224   5.        ]
 [11.22536194 -0.2760382  -0.27878969  0.52888209  1.31637291  0.61502212
  -0.28369851 -0.07372774  5.        ]
 [-4.27187385 -0.2760382   0.17376645  0.64196174  1.31637291  0.70620582
  -0.1875634  -0.07372774  3.        ]
 [-4.27187385  4.37450371  0.1507594  -0.34861599  1.31637291  0.833863
   0.19697704  0.37766767  5.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-1.13464578e+00  8.36546451e-02  4.66522843e-01 -6.87593476e-02
   1.52131494e+00  1.15559203e+00  8.68359620e-01  9.64038010e-01
   4.00000000e+00]
 [ 6.33888774e+00  6.69571780e+00  1.17313263e+00  8.16008289e-01
   1.06872260e+00  1.06867630e+00  1.32036372e-01  5.33689890e-03
   4.00000000e+00]
 [ 6.33888774e+00  3.38968622e+00  2.06192920e-01  9.92527308e-01
  -8.17078815e-01 -7.56553853e-01 -8.49727959e-01 -4.74013656e-01
   4.00000000e+00]
 [ 1.00756545e+01  3.38968622e+00  3.54952876e-01 -1.12135584e+00
  -8.17078815e-01 -7.56553853e-01 -8.49727959e-01 -4.74013656e-01
   4.00000000e+00]
 [ 6.33888774e+00  6.69571780e+00  1.69002931e-01  1.20380699e+00
  -8.17078815e-01 -7.56553853e-01 -8.49727959e-01 -4.74013656e-01
   4.00000000e+00]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-3.41581057 -1.42138239 -0.19586372 -0.22630267  1.40729706  1.581294
   1.51546376  2.52683311  1.        ]
 [-3.41581057 -1.42138239 -0.44510575 -0.35885367  0.91674919  0.98284029
   1.00542259  1.46517     1.        ]
 [-6.36707091 -4.693339   -0.66235951 -0.57380124  0.91674919  1.00018677
   1.00542259  1.54574264  1.        ]
 [ 2.4867101   1.85057423  0.50454638  0.03470509  0.91674919  1.21701783
   1.21793974  1.73058578  1.        ]
 [-3.41581057 -1.42138239  0.13001691 -0.28720448  0.91674919  1.26038404
   1.26044317  1.95334545  1.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)

[[ 9.76514801  6.33980579  0.70044563  0.57150088 -0.41032311 -0.60299565
  -0.50385757 -0.23045217  4.        ]
 [-2.20572422 -8.16477035 -0.13303135 -0.52413898 -0.41032311  2.10100129
   2.28297997  6.40013128  4.        ]
 [-8.19116034 -8.16477035  0.1425717  -0.49367837 -0.41032311  2.17215911
   2.0971908   7.34735749  4.        ]
 [-2.20572422  1.50494708 -0.45753173 -0.33478076 -0.41032311 -0.60299565
  -0.50385757 -0.23045217  4.        ]
 [ 9.76514801 11.17466451  2.03400881  0.42171005 -0.41032311 -0.60299565
  -0.50385757 -0.23045217  4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(

[[-3.21103324e+00 -3.65541963e+00 -5.24581264e-01 -1.43023775e-01
  -2.05900076e-01 -2.54098033e-01 -1.02686939e+00 -1.77291084e+00
   1.00000000e+00]
 [ 4.54529819e-01 -2.13404912e-01 -4.31258780e-01  3.31856555e-02
  -4.98787808e-01 -2.64510180e-01 -1.05350949e+00 -1.89625235e+00
   1.00000000e+00]
 [-3.21103324e+00 -3.65541963e+00 -3.88674733e-01 -1.12344455e-01
  -3.52343942e-01  1.31151403e-01 -6.80548058e-01 -9.54371742e-01
   1.00000000e+00]
 [-6.87659630e+00 -3.65541963e+00 -4.94379813e-01 -3.87671690e-01
  -5.94562096e-02  6.67376969e-01 -1.74386111e-01 -7.97683175e-02
   1.00000000e+00]
 [-3.21103324e+00 -3.65541963e+00 -5.03742263e-01 -2.73607550e-01
   3.79875388e-01  1.02138996e+00  1.20946065e-02 -1.27826654e-03
   1.00000000e+00]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-6.72196983 -6.08005672 -0.36619485 -0.88735113  1.65934496  0.75408487
   0.85875388  1.47494081  1.        ]
 [ 8.28242711 -2.00221854 -0.17408259 -0.09374188  1.65934496  0.75408487
   1.19234554  2.34077404  3.        ]
 [ 0.78022864 -6.08005672 -0.21997057 -0.32127469  2.74317576  1.13583556
   1.85952886  2.98710025  4.        ]
 [ 4.53132787  2.07561963 -0.11526222 -0.65430714  3.01413346  2.1538374
   2.37103607  2.70661907  4.        ]
 [ 8.28242711  2.07561963 -0.05096763 -0.21183849  2.74317576  1.77208671
   2.21535996  2.85295708  4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[-1.76730039 -4.31760488 -0.4176584  -0.48047464  0.          0.
  -0.22098025 -0.09035079  1.        ]
 [ 7.74819161  3.41028211 -0.22621473  0.37699062  0.          0.
  -0.22098025 -0.09035079  4.        ]
 [ 2.99044561  3.41028211 -0.30649935  0.70460706  0.          0.
  -0.22098025 -0.09035079  4.        ]
 [-1.76730039 -0.45366138 -0.37339397 -0.28147799  0.          0.
  -0.22098025 -0.09035079  4.        ]
 [ 5.36931861  3.41028211 -0.18477216  0.99015917  0.          0.
  -0.22098025 -0.09035079  3.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

[[11.46678918  4.46885656  0.13945337  0.66006859 -0.35100064 -0.69356087
  -0.70187241 -0.66429818  4.        ]
 [-0.27217353 -4.27494168 -0.65152789 -0.67174792 -0.35100064 -0.69356087
  -0.70187241 -0.66429818  4.        ]
 [-0.27217353  0.09695744  0.42776564  0.03419912 -0.35100064 -0.69356087
  -0.70187241 -0.66429818  4.        ]
 [ 5.59730782  8.84075569  1.85535338  0.69800007 -0.35100064 -0.69356087
  -0.70187241 -0.66429818  4.        ]
 [-0.27217353 -4.27494168  0.04599055  0.22385654 -0.35100064 -0.69356087
  -0.70187241 -0.66429818  4.        ]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

In [109]:
MSE

{'AL': [196.44263010236315],
 'DC': [4103.505229235348],
 'IL': [4123.311559305501],
 'NV': [3370.2763561042148],
 'AZ': [3650.919485924034],
 'PA': [4486.221057199953],
 'GA': [3277.817322608156],
 'CA': [5801.788679329825],
 'TX': [4549.990626908995],
 'NY': [3034.7153168086597],
 'FL': [4007.596964029508],
 'MA': [2779.149382247523],
 'MI': [3283.077677731503]}

In [110]:
# for key,value in MSE.items():
        
#     plt.plot(range(2, 40), value, marker='o')
#     plt.title(f'Elbow Method: {key}')
#     plt.xlabel('Number of clusters')
#     plt.ylabel('Sum of Squared Distances')
#     plt.show()

Select State here

In [111]:
df_check=dfs_by_category['NY'].drop(columns=['description','homeInsights','image_captions','address.city','address.state','address.zipcode'])
print(df_check)
scaler=StandardScaler()

df_to_transform = df_check.drop(columns=['homeType'])
df_excluded = df_check[['homeType']]
# Apply the transformation
transformed_array = scaler.fit_transform(df_to_transform)
df_transformed = pd.DataFrame(transformed_array, columns=df_to_transform.columns, index=df_check.index)
# Recombine the DataFrame
df_result = pd.concat([df_transformed, df_excluded], axis=1)
# print(df_result)
X=df_result.values
weights = [5,5,1,1,1,1,1,1,1]
X=X*weights
print(X[:5])
sse = []           
kmeans = KMeans(n_clusters=12,init='k-means++', random_state=42)
if(key=='CA'):
    kmeans = KMeans(n_clusters=24,init='k-means++', random_state=42)

kmeans.fit(X)
kmeans.labels_

            bedrooms  bathrooms    price  homeType   livingArea  \
zpid
31491229         1.0        1.0   650000         1   776.000000
31492996         2.0        2.0   959000         1  1000.000000
31493494         1.0        1.0  1100000         1   815.000000
31494186         0.0        1.0   750000         1   465.000000
31494718         1.0        1.0   719000         1   610.000000
...              ...        ...      ...       ...          ...
2126607850       1.0        1.0   920000         1   830.000000
2138952719       2.0        3.0  2750000         0  1250.000000
2139216295       1.0        1.0  1065000         1   955.000000
2139216605       1.0        1.0  1100000         1   841.000000
2139218516       2.0        1.0  1295000         1  1820.995024

            leisure_within_5km  shops_within_5km  schools_within_5km  \
zpid
31491229                    21               540                 128
31492996                    19               538                 127
31493494                    20               614                 141
31494186                    22               717                 160
31494718                    25               785                 167
...                        ...               ...                 ...
2126607850                  21               633                 150
2138952719                  24               729                 170
2139216295                  19               622                 148
2139216605                  19               595                 152
2139218516                  23               493                 185

            transit_within_2km
zpid
31491229                   121
31492996                   110
31493494                   194
31494186                   272
31494718                   279
...                        ...
2126607850                 153
2138952719                 391
2139216295                 143
2139216605                 277
2139218516                 278

[500 rows x 9 columns]
[[-3.21103324e+00 -3.65541963e+00 -5.24581264e-01 -1.43023775e-01
  -2.05900076e-01 -2.54098033e-01 -1.02686939e+00 -1.77291084e+00
   1.00000000e+00]
 [ 4.54529819e-01 -2.13404912e-01 -4.31258780e-01  3.31856555e-02
  -4.98787808e-01 -2.64510180e-01 -1.05350949e+00 -1.89625235e+00
   1.00000000e+00]
 [-3.21103324e+00 -3.65541963e+00 -3.88674733e-01 -1.12344455e-01
  -3.52343942e-01  1.31151403e-01 -6.80548058e-01 -9.54371742e-01
   1.00000000e+00]
 [-6.87659630e+00 -3.65541963e+00 -4.94379813e-01 -3.87671690e-01
  -5.94562096e-02  6.67376969e-01 -1.74386111e-01 -7.97683175e-02
   1.00000000e+00]
 [-3.21103324e+00 -3.65541963e+00 -5.03742263e-01 -2.73607550e-01
   3.79875388e-01  1.02138996e+00  1.20946065e-02 -1.27826654e-03
   1.00000000e+00]]

c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\kalya\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

array([ 3,  2,  3,  6,  3,  2,  3,  2, 10,  3,  3,  7,  3,  2, 10,  6,  6,
        3,  2,  3,  6,  3,  2,  2,  1,  3, 11,  2,  3,  2,  3,  2,  6,  1,
       10,  6, 11,  1, 10, 10,  2,  6,  3, 10,  3,  2,  2, 10,  1,  2,  6,
        8,  5, 10,  1,  7,  3,  8,  1,  2,  8,  2,  6,  3,  1,  3,  9,  3,
        2,  3,  3,  1,  6,  3,  3,  6, 10,  9,  3,  3,  6,  3,  3,  9,  3,
        2, 10,  2,  3, 10,  2, 10,  3,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        3, 10,  3,  3,  3,  9,  2, 10,  3,  3,  2,  1, 10,  3,  2,  0, 10,
        3,  2, 11,  2,  2, 10,  2,  2, 11,  3,  3,  9,  3, 11,  2,  6,  3,
       11,  9,  6,  0,  2,  2,  9,  2,  2,  1,  2,  3,  3,  6,  3,  3,  6,
        2,  2,  9, 11,  3,  6,  2,  6,  1,  2, 10,  6, 11, 10,  1,  6,  3,
        0, 10,  0,  3,  2,  3, 11,  1,  2,  9,  2,  3,  0,  3,  2,  6,  0,
        6,  6, 10,  2,  2,  3,  3,  3,  3,  3,  3,  2,  3,  3,  2,  3,  3,
        3,  3,  3,  2,  2,  2,  1,  6,  2,  3,  2, 11,  3,  3,  0, 10,  3,
        3,  3,  3, 10,  9,  2,  0,  2,  3, 10,  3,  3, 11,  2,  7,  8,  6,
        3,  3,  2,  3,  6,  3, 10,  3,  2, 10,  8,  7, 10,  6,  6, 10,  9,
        7,  1,  7,  3,  6,  9,  3,  2,  2, 11,  6,  3,  2,  3,  3, 10, 10,
       11, 10,  6,  7,  3,  3,  9,  2, 10, 11,  6,  6,  6,  3, 10,  3,  2,
        3,  3,  3, 10,  3,  9,  2,  3,  3,  2,  3,  2, 11,  6,  6,  6,  6,
        3,  2, 10,  3,  3,  3,  2,  7, 10,  9,  3,  3,  3,  3,  9,  2,  1,
       10,  6,  2,  2,  3,  3,  3,  2,  3,  2,  0,  0,  0,  3,  2,  1,  7,
       10,  3,  9,  3,  6,  3,  6,  9,  9,  1,  9,  3,  2,  7,  0,  0,  0,
        0,  9,  1,  1, 11,  3,  9,  0,  3,  9,  9,  9,  9,  1,  9,  9, 11,
        9,  9,  7,  1,  1,  2,  4,  3,  2, 10,  3, 10, 10, 10,  2,  2,  2,
       10, 10,  7, 10,  6, 10,  9,  2,  2,  3, 10,  1,  9,  3, 10, 10,  9,
        1,  3, 10,  3,  3,  9,  3,  6,  2,  3,  9,  8, 11,  1,  3,  2,  2,
       10,  3,  2, 10,  2,  2, 10,  2,  7,  6, 10,  1,  2, 11,  3,  1,  3,
        1,  9,  7,  2, 10,  9, 10,  3,  3,  7,  0,  2,  2,  3, 11,  5,  9,
        2,  3,  8,  3,  7,  1,  1,  2,  2,  3,  2,  2,  9,  7,  9, 10,  6,
        2,  9, 11,  9,  6,  9,  9, 11,  2, 10, 11, 11,  2,  3,  3,  3,  2,
        1,  3,  3,  9,  3,  3,  2])

In [112]:
kmeans.cluster_centers_

array([[-1.91730510e+00, -2.64306236e+00, -3.86933708e-01,
        -5.41577301e-01, -3.28122126e+00, -3.06537770e+00,
        -4.43680251e+00, -3.12966744e+00,  1.00000000e+00],
       [ 6.52561863e+00,  7.42356524e+00,  1.12836305e+00,
         1.32287251e+00, -2.74216139e-02,  4.34616027e-02,
         6.45423083e-02, -1.62866856e-03,  1.28125000e+00],
       [ 5.25021417e-01, -1.10700489e+00, -2.01993467e-01,
        -1.42804496e-01,  2.65818147e-01, -4.79074894e-02,
         1.87048356e-01,  9.93459787e-03,  9.61538462e-01],
       [-3.21103324e+00, -3.65541963e+00, -4.39409065e-01,
        -4.63120557e-01,  1.34806062e-01,  1.59200451e-01,
         1.64142538e-01,  9.92561233e-02,  9.65986395e-01],
       [ 4.54529819e-01,  3.42067422e+01,  4.81127067e-01,
         2.55807392e-01, -2.05900076e-01,  2.56097165e-01,
        -4.11855984e-02,  7.72409378e-01,  1.00000000e+00],
       [ 2.61134712e+01,  1.18336466e+01, -1.17012678e-01,
         2.28300249e+00,  3.16230884e+00, -1.78988970e+00,
         7.44697425e-01, -2.81599877e-01,  3.00000000e+00],
       [-6.87659630e+00, -3.58059322e+00, -5.38063619e-01,
        -5.49447988e-01,  7.10698449e-02,  3.09516006e-01,
         6.65330768e-02,  1.69108521e-01,  9.56521739e-01],
       [ 1.05887336e+01,  1.15299394e+01,  2.30671598e+00,
         2.44019352e+00, -2.23128766e-01,  4.90791857e-02,
         9.82831734e-02, -6.72362925e-02,  1.82352941e+00],
       [ 1.66877376e+01,  1.99469670e+01,  4.18015769e+00,
         3.34643989e+00,  1.91590418e-01, -1.23202472e-01,
         3.87347090e-02,  8.33276010e-03,  2.28571429e+00],
       [ 4.54529819e-01,  3.22860980e+00,  2.87102863e-01,
         3.49663387e-01,  9.02419645e-02,  2.61881692e-01,
         1.71935221e-01,  4.50226407e-01,  9.77777778e-01],
       [ 4.62568778e+00,  1.38891228e+00,  6.28577938e-02,
        -1.25039413e-01,  3.39648773e-02, -4.04695018e-02,
         1.95360139e-01,  2.67538945e-02,  1.00000000e+00],
       [-3.36376503e+00,  2.16846927e-01, -1.86088456e-01,
        -1.30535718e-01, -1.57085454e-01,  4.99047260e-01,
         1.77485243e-01,  3.71549475e-01,  1.12500000e+00]])

In [113]:
weights

[5, 5, 1, 1, 1, 1, 1, 1, 1]

In [114]:
cluster_centers = kmeans.cluster_centers_

# Since we applied weights, we need to reverse this before denormalization
cluster_centers_unweighted = cluster_centers /weights

cluster_centers_to_denorm = cluster_centers_unweighted[:,:-1]
# print(cluster_centers_to_denorm)
# Denormalize the cluster centers
cluster_centers_denormalized = scaler.inverse_transform(cluster_centers_to_denorm)

cluster_centers_final= np.concatenate((cluster_centers_denormalized,cluster_centers_unweighted[:,-1].reshape(-1, 1)),axis=1)
cluster_centers_final

array([[ 1.35294118e+00,  1.29411765e+00,  1.10576471e+06,
         2.69352941e+02, -3.55271368e-15,  0.00000000e+00,
         0.00000000e+00,  5.68434189e-14,  1.00000000e+00],
       [ 3.65625000e+00,  4.21875000e+00,  6.12306250e+06,
         2.63946875e+03,  2.22187500e+01,  5.97156250e+02,
         1.68968750e+02,  2.78968750e+02,  1.28125000e+00],
       [ 2.01923077e+00,  1.74038462e+00,  1.71812018e+06,
         7.76278750e+02,  2.42211538e+01,  5.79605769e+02,
         1.73567308e+02,  2.80000000e+02,  9.61538462e-01],
       [ 1.00000000e+00,  1.00000000e+00,  9.32013599e+05,
         3.69088300e+02,  2.33265306e+01,  6.19387755e+02,
         1.72707483e+02,  2.87965986e+02,  9.65986395e-01],
       [ 2.00000000e+00,  1.20000000e+01,  3.98000000e+06,
         1.28300000e+03,  2.10000000e+01,  6.38000000e+02,
         1.65000000e+02,  3.48000000e+02,  1.00000000e+00],
       [ 9.00000000e+00,  5.50000000e+00,  1.99950000e+06,
         3.86000000e+03,  4.40000000e+01,  2.45000000e+02,
         1.94500000e+02,  2.54000000e+02,  3.00000000e+00],
       [ 0.00000000e+00,  1.02173913e+00,  6.05358587e+05,
         2.59347610e+02,  2.28913043e+01,  6.48260870e+02,
         1.69043478e+02,  2.94195652e+02,  9.56521739e-01],
       [ 4.76470588e+00,  5.41176471e+00,  1.00247059e+07,
         4.05982353e+03,  2.08823529e+01,  5.98235294e+02,
         1.70235294e+02,  2.73117647e+02,  1.82352941e+00],
       [ 6.42857143e+00,  7.85714286e+00,  1.62278571e+07,
         5.21185714e+03,  2.37142857e+01,  5.65142857e+02,
         1.68000000e+02,  2.79857143e+02,  2.28571429e+00],
       [ 2.00000000e+00,  3.00000000e+00,  3.33756662e+06,
         1.40231111e+03,  2.30222222e+01,  6.39111111e+02,
         1.73000000e+02,  3.19266667e+02,  9.77777778e-01],
       [ 3.13793103e+00,  2.46551724e+00,  2.59506897e+06,
         7.98861983e+02,  2.26379310e+01,  5.81034483e+02,
         1.73879310e+02,  2.81500000e+02,  1.00000000e+00],
       [ 9.58333333e-01,  2.12500000e+00,  1.77078325e+06,
         7.91875000e+02,  2.13333333e+01,  6.84666667e+02,
         1.73208333e+02,  3.12250000e+02,  1.12500000e+00]])

In [115]:
homeT=df_check['homeType']
df_check=df_check.drop(columns=['homeType'])

In [116]:
cols=list(df_check.columns.values)
cols = cols + ['homeType']
print(cols)
df_cluster_centers=pd.DataFrame(cluster_centers_final,columns=list(cols))
np.floor(df_cluster_centers)

['bedrooms', 'bathrooms', 'price', 'livingArea', 'leisure_within_5km', 'shops_within_5km', 'schools_within_5km', 'transit_within_2km', 'homeType']

,bedrooms,bathrooms,price,livingArea,leisure_within_5km,shops_within_5km,schools_within_5km,transit_within_2km,homeType
0,1.0,1.0,1105764.0,269.0,-1.0,0.0,0.0,0.0,1.0
1,3.0,4.0,6123062.0,2639.0,22.0,597.0,168.0,278.0,1.0
2,2.0,1.0,1718120.0,776.0,24.0,579.0,173.0,280.0,0.0
3,1.0,1.0,932013.0,369.0,23.0,619.0,172.0,287.0,0.0
4,2.0,12.0,3980000.0,1283.0,21.0,638.0,165.0,348.0,1.0
5,9.0,5.0,1999500.0,3860.0,44.0,245.0,194.0,254.0,3.0
6,0.0,1.0,605358.0,259.0,22.0,648.0,169.0,294.0,0.0
7,4.0,5.0,10024705.0,4059.0,20.0,598.0,170.0,273.0,1.0
8,6.0,7.0,16227857.0,5211.0,23.0,565.0,168.0,279.0,2.0
9,2.0,3.0,3337566.0,1402.0,23.0,639.0,173.0,319.0,0.0
10,3.0,2.0,2595068.0,798.0,22.0,581.0,173.0,281.0,1.0
11,0.0,2.0,1770783.0,791.0,21.0,684.0,173.0,312.0,1.0

In [131]:
predict_X=[2,1,1700000,2000,20,400,250,200,2]
df_predict = pd.DataFrame([predict_X],columns=cols)
scaler_predict=StandardScaler()

df_to_transform_p = df_predict.drop(columns=['homeType'])
df_excluded_p = df_predict[['homeType']]
# Apply the transformation
transformed_array_p = scaler.transform(df_to_transform_p)
print(transformed_array_p)
df_transformed_p = pd.DataFrame(transformed_array_p, columns=df_to_transform_p.columns, index=df_predict.index)
# Recombine the DataFrame
df_result_p = pd.concat([df_transformed_p, df_excluded_p], axis=1)
# print(df_result)
X_p=df_result_p.values
# weights = [5,5,1,1,1,1,1,1,1]
X_p=X_p*weights
X_p

[[ 0.09090596 -0.73108393 -0.20746602  0.8198349  -0.35234394 -0.98294832
   2.22322311 -0.88709456]]

array([[ 0.45452982, -3.65541963, -0.20746602,  0.8198349 , -0.35234394,
        -0.98294832,  2.22322311, -0.88709456,  2.        ]])

In [132]:
kmeans.predict(X_p)

array([2])